name: Validate pipeline

on:
  pull_request:
    paths: ['release.yml', 'release.yaml']

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: wolfware-labs/setup-moonlit@v1

      - run: moonlit validate
